name: Scrape Website

on:
  workflow_dispatch:  # Permet de lancer manuellement
  push:
    paths:
      - scrape.py

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install playwright
          playwright install chromium

      - name: Run scraper
        run: |
          python scrape.py https://example.com
